language: java
addons:
  ssh_known_hosts:
    secure: SRI2bsHvxfRUrzj5i6D/JkWeM0s/8fC4B/eFUt3VKDUbvQr87GpZlnJQBcT6vXp692lieVCBliu7y5NJloDrbjPjs8jO0ry2nXbnqiZAf460PsNAcvF5ZLdz5SUFyevikDvxCmXEgItzbZ7BJktIPqFD9gviiFtbjWmdtkjiIp5GGj9eud5cny1Zkg3spVQyEdYDJNwB83Ednf4CkYAJlw1LBQBeJgZqbBmlr1K5L7IKeMlQan20xOVggaw1QgWTgqF/2fZbyXtwY8mB63e1pXlSyo4xRAWdYiDbJLDz1u2ywbPkfo7kflJMzn1uqiQSFhdePIC4ojDML0Cdjd089rT1nBVN/u5me1gLW9TBOIxCtKpxEUdDvImLbYPQ2oHezJUWzZ88fbynD9ZnmW4kZY4c0TtD8JYqXy9t70BsDhpGNn5VnYjoQIR/tWFwTcxLmrRV+pP7/jiPEB0CFpvioSEIQHcxNUJUY55bxL0p7q59aU0VP5e6usgDNLqBAzjIk/zzTt2MZ7y2+zzUa9ip7KOkAG1tty79PF8Gq0ovidoF8WEfXku7vM1b9WBal4N5phKfU+ilcLiC1v2abHoNWB/zK5bhEClLzYg/5kz9otwFQxisvygX1qfMctfPY0grQ0CZHEV0yHwN/e3YnQO866//MQg3fjZLZwPJaQ1Jox8=
jdk:
- oraclejdk8
script: mvn clean package -Dmaven.test.skip=true
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - secure: EFUTsaWe4seJrqLmZBbycNgY0+tarih3XHqqte+jHfxEWk4C+mFkwVZ4ESLqDGsf5XCT8aSaKx0ISd5GqAb4Ie5poEoIk4AFi+slKbRVHHL6fxnxt4VIUt81TJ0IFNKLj98LJAZ7AHFYrjg97+WSes53s1BA2xVwub9CYZHTqLz8DQkkxymAt5h8cJ80gNv72G/sU228Qmwyr7WB0i3NANF7YJsY1dGy+GL/F1KNvFpJqtLmF+2UDrI/tuif7hDp0uDkwhmL23CkhF9G714jpbwl8iP/O7nHvQccnToytVgqpO4WHz7A6oxeK2qpZ1AMB/uwDWNPW8KuVhzDi9Cv2D0BrNL6AHPKqMWdyZ74sTtM+Assjuyza9RCFZfEmMMvU8UMUHvQqgOhMYJAr663f6Ih1YHbZDmrc/y4rFZACi0LYiE0xOGrvLB7UtZPShgkIQ30NYBBD+nIwY6Fii2dGHAW7Mp+7dzXRWHq6v1fBvDGYokAcCK0DpnulSY8VmHPMD3FsWmnb2vfMp3DoQnD3LYbp7w6mbOZYi1XY7Qp9Ex3NcUR9f/9mrb3CWNld8JyL6GACcFIRw797O/JT667pJCFXrcYrqmxAYonKr7iqq7i5ffjp+eshJns5ogmIAo+G5UNI2c9/c4AeeMBtmQ/tR4JwBCP8JKeuKtlxDyeZIw=
    on_success: always
    on_failure: always
after_success:
- ssh $SERVER_USER@$SERVER_HOST "sh ./deploy-to-vps.sh "
before_install:
- openssl aes-256-cbc -K $encrypted_d0588f4484d8_key -iv $encrypted_d0588f4484d8_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa