language: java
addons:
  ssh_known_hosts:
    secure: "DvMi9EjXbdKzsbEjOxnpazxv1kXn9dwB6LP6Njrte26XPmkfGuXWp2gpKCVX8itULrOa/lYZqlxlpMAFKKkbBgmqcE44xYxPk1FPY9tofeMzoEn/VFVGQvS8rC39s10Xah3rHOqp6n5pdP/S6d3RHPi06+O7W1fsmKA9yPpIs1qo4pmR6sPFf2NtCJXESynzZJVo0MtdonAF16O2vUVo35V9eC88i3ywr15ip1cMQkdd3E52ciGuC18YOU0aSrgcpFS8wEe7Yo263HEJykS4Td4rOIwok3u6Rh3hnrKitzPAhZcmCF5sIqUSznOCuRBewbup6RtWm0Y0F9UEgcgDkZAUtwYPQVLBimDjFMY+zwXtp/I7SVFvjxk5PKHNyGCVaTXKxfb7+Knvds8CkanKyc8az0IndUfyv+WgOWeCpLdRr8Mj0lia/3/xBkYyPB31KLmyaCBK1u0Hfg8Cu8/RSDuDbmKZ4qGVp+RRWC3nKjhA4ILoF6grxKm/WVwSxNv3/2BWvGCm93MRvYO34wiItdHJiFa8YFmP0aXajLJ6sxZPRLp/mib1qUUHQUfCPNNtkcO/7ugDIVYcxdxvibmSrKtBqB+FNYSIaQGQ14TPnf8KXiVtI2UUSw1PYd5HUHtNT7HgEI2V++q+c2aI2H6EcJI2TpGzc2BSSWTqsL+OgWE="
jdk:
- oraclejdk8
script: mvn clean package -Dmaven.test.skip=true
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - $EMAIL
    on_success: always
    on_failure: always
after_success:
- ssh $SERVER_USER@$SERVER_HOST "sh ./deploy-to-vps.sh "
before_install:
- openssl aes-256-cbc -K $encrypted_decfd95f65ce_key -iv $encrypted_decfd95f65ce_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
env:
  global:
  - secure: Q8P/2mUIQm3nNL5EBoHjxnRIi4OH2U2oTCDlRAHw3fz22WUW5zwETE27/buWnLXTdFKTZUPCeSzNoSc8VRqdLYnJmSxm2Jcu0jq9SHgw3KYbAphDgRIbxo9O4ryO/8Y41aIn9q1h0HQ4NpctHggrdG6KULH8v4jYAtT9FBKSL5Xfc0QxNd8pRtmtR29XCsA8G+YOd0FpzTdtguLCKcbLmEzUH2LlqgGHWblmNiQUByXq7qU6e47U90j/QDk38RBw/VBVuxR1J+apx56Xr1bA64yPYVVHtx2sPX8beSCuqMZEe9iVMQuXz8PqZ07FTmcCnFBMOkU7G/qEAYW7w9JRCEZNWr82SHy00aRNnAUsm+OFT7uLbsytvybmd9lTS4h8f72Cr1Hp5OcmM3KBE8VaOVUN2a8gQDL6hP5BQ7l9LWVFCXTW3FshDKTT1E0Fe34KT0+q0+Cv90FjQt9iNOP4EYp0i6xuMfQbAoxQEqXtmKCuG5OFyg1hv6YarvVi5U8/5uHcORyOeqKshN6uifaHeiji6O80pVkZjiqzNhqu8rmFkbLLRQhTwleuHjNteuhyzQsA5mHe1mZjzYkVpiHCf2gMw2/1ANukIp2K8t/wnHtUNXdoFUtOipRaOdyvjJXPp0DGq0YDchxTJzuwlS4PWdwGM1HWUKlttTWBLAhL6mg=
