language: java
addons:
  ssh_known_hosts:
    secure: "DvMi9EjXbdKzsbEjOxnpazxv1kXn9dwB6LP6Njrte26XPmkfGuXWp2gpKCVX8itULrOa/lYZqlxlpMAFKKkbBgmqcE44xYxPk1FPY9tofeMzoEn/VFVGQvS8rC39s10Xah3rHOqp6n5pdP/S6d3RHPi06+O7W1fsmKA9yPpIs1qo4pmR6sPFf2NtCJXESynzZJVo0MtdonAF16O2vUVo35V9eC88i3ywr15ip1cMQkdd3E52ciGuC18YOU0aSrgcpFS8wEe7Yo263HEJykS4Td4rOIwok3u6Rh3hnrKitzPAhZcmCF5sIqUSznOCuRBewbup6RtWm0Y0F9UEgcgDkZAUtwYPQVLBimDjFMY+zwXtp/I7SVFvjxk5PKHNyGCVaTXKxfb7+Knvds8CkanKyc8az0IndUfyv+WgOWeCpLdRr8Mj0lia/3/xBkYyPB31KLmyaCBK1u0Hfg8Cu8/RSDuDbmKZ4qGVp+RRWC3nKjhA4ILoF6grxKm/WVwSxNv3/2BWvGCm93MRvYO34wiItdHJiFa8YFmP0aXajLJ6sxZPRLp/mib1qUUHQUfCPNNtkcO/7ugDIVYcxdxvibmSrKtBqB+FNYSIaQGQ14TPnf8KXiVtI2UUSw1PYd5HUHtNT7HgEI2V++q+c2aI2H6EcJI2TpGzc2BSSWTqsL+OgWE="
jdk:
- oraclejdk8
script: mvn clean package -Dmaven.test.skip=true
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - secure: "NxCQ+Cjh1pC0NVmb+5D0VPlGfMM0F8nKWgpVmgnZm0iVGLSI05ra9KuJfrs0FqkdndSS0eFK4bANNdswyEeCUfmC4tjQwFNPHFP+IgdgOlCFgeqMo8ZelhRq+SOuo7p6m8wsxavPR8mrKfF/57XuDy5xGzuaS9fmiqepb3TK8z7gx9UJXnS0sVT04Q01d54fRKeHaxC4azKBRqQA+jryAotwlcWKDbKeFIXe7YAVrmPryeVq5kan8rIMkfHAZJv/3D/Cie/nEJGQCCgAEvttlFYMMymm9kHLrhzxJpHcvdoZOTSC3M3WPIqnAmKngIweFdkOJDIoEKnrltYX3OQdAXtTUJYoT2KVeIs5be4eZJmc7BvYTuUlyWnFpVvztkSgJ3JfdHI+XOFEdS/GvtuDB7z0Rbe4d5R9Cf7rCVfGXfNAveLivfa2h/o4Kh97ymxKHI3ak1f8p/INvpozKZypBQ5Hwu31JvQkmftZTJNRCXdKB1fQWviwjX6iWz401zFz4KEXpFtox12ScChxuGvrD9qSSBRz0+pLVTN6moT710xe1MAV3XjWU8ygulgco+bpz36ijYEHmSuOxLY0wNR06a7R/PRkBoC9pn254Jcn00X2yRWYIqbbtstrnofup8kJGJmkDNL8yrKSHSTnElBMo7Hd0mVP8mM5AEbQYTTBWrM="
    on_success: always
    on_failure: always
after_success:
- ssh $SERVER_USER@$SERVER_HOST "sh ./deploy-honeypotato.sh "
before_install:
- openssl aes-256-cbc -K $encrypted_decfd95f65ce_key -iv $encrypted_decfd95f65ce_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa