language: java
addons:
  ssh_known_hosts: ${HOSTIP}
jdk:
- oraclejdk8
script: mvn clean package -Dmaven.test.skip=true
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - secure: EFUTsaWe4seJrqLmZBbycNgY0+tarih3XHqqte+jHfxEWk4C+mFkwVZ4ESLqDGsf5XCT8aSaKx0ISd5GqAb4Ie5poEoIk4AFi+slKbRVHHL6fxnxt4VIUt81TJ0IFNKLj98LJAZ7AHFYrjg97+WSes53s1BA2xVwub9CYZHTqLz8DQkkxymAt5h8cJ80gNv72G/sU228Qmwyr7WB0i3NANF7YJsY1dGy+GL/F1KNvFpJqtLmF+2UDrI/tuif7hDp0uDkwhmL23CkhF9G714jpbwl8iP/O7nHvQccnToytVgqpO4WHz7A6oxeK2qpZ1AMB/uwDWNPW8KuVhzDi9Cv2D0BrNL6AHPKqMWdyZ74sTtM+Assjuyza9RCFZfEmMMvU8UMUHvQqgOhMYJAr663f6Ih1YHbZDmrc/y4rFZACi0LYiE0xOGrvLB7UtZPShgkIQ30NYBBD+nIwY6Fii2dGHAW7Mp+7dzXRWHq6v1fBvDGYokAcCK0DpnulSY8VmHPMD3FsWmnb2vfMp3DoQnD3LYbp7w6mbOZYi1XY7Qp9Ex3NcUR9f/9mrb3CWNld8JyL6GACcFIRw797O/JT667pJCFXrcYrqmxAYonKr7iqq7i5ffjp+eshJns5ogmIAo+G5UNI2c9/c4AeeMBtmQ/tR4JwBCP8JKeuKtlxDyeZIw=
    on_success: always
    on_failure: always
after_success:
- ssh $SERVER_USER@$SERVER_HOST "sh ./deploy-to-vps.sh "
before_install:
- openssl aes-256-cbc -K $encrypted_decfd95f65ce_key -iv $encrypted_decfd95f65ce_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
env:
  global:
    secure: XhFEW0ATmeEerDrW+BMUhYW7LbIe1i74BUXdVYcNwqBCvJf4JQ0shNgy3OWHe8WlfIFWfkyfA6nZecd07GKEoN5O+70YwjlJhVwbMvKxDrDOH/pTowlcaV4SUsnRQm8pUy069uALwJjWEzXNALIfpxVj+CE+oEgBdXIw+uE/KxcX7TL7mYuzr1WrmVwKsB5rYzf4sw5kWL4GmwjoZxkitPi8FfwDJh1fHWWPf2BtHP+sMBxHYQfboR1boliwbuGl716U1dCSYwxpsyKzz3DkadAJuRFQCadR5SlHt/2gqcQhetBnxNqh57HXHK2NzXV1wfR2uWhpL1/pW8HicidgxEI2+Zp5iulrCrgnbUm9lkT8XD8eKdyvOsady+gl6xi8zCvfuEUznlb2L1GJx+iksbNsg9R6y3KfaBHsSUmE5LzprIYE2BCTN4TfT2VA+2LJoBPQDzL1pm+ZB7VEl9Hdp0CdUsrN8DeopMh1YjG9nvuxF46s7fzpS9deRc1fZdiIhANk/S7b2Y2eGrWKZDHMxBUM5RZOv6r1qCzl2MhfhzM4D6uiLHdiZJa4/JlozSPNZ5x1jGmhVlvv3TYDRgrvCIex76a5bKbZmprWnL4WFIRtpXbykbvlwJE1/EuG/78yWY6ey5GXRZUa4YZtzKOTaLysNj1J+jjXKt3pIa5tTq8=
