server:
  port: 9000
eureka:
  instance:
    hostname: ali-server1
  client:
    # register-with-eureka: false
    # fetch-registry: false
    serviceUrl:
      defaultZone: http://ali-server2:9000/eureka/